# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # ref: https://hub.docker.com/r/circleci/php/tags/
      - image: circleci/php:7.1-cli

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: composer install -n --prefer-dist
      - run:
          command: wget http://www.phpdoc.org/phpDocumentor.phar

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run:
          name: PHP Documentor
          command: |
            mkdir -p ~/phpdoc
            php phpDocumentor.phar
          when: always
      - store_artifacts:
          path: php/tmp/docs

      - run:
          name: PHP CodeSniffer
          command: vendor/bin/phpcs -n
          when: always

      - run:
          name: PHPUnit
          command: |
            mkdir -p ~/phpunit ~/coverage
            vendor/bin/phpunit --log-junit ~/phpunit/junit.xml --coverage-html ~/coverage
          when: always
      - store_test_results:
          path: ~/phpunit
      - store_artifacts:
          path: ~/coverage
